export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAILURE = 'GET_SERVICES_FAILURE';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_FAILURE';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAILURE = 'UPDATE_SERVICE_FAILURE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';

export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';
export const CREATE_LOCATIONS_SUCCESS = 'CREATE_LOCATIONS_SUCCESS';
export const CREATE_LOCATIONS_FAILURE = 'CREATE_LOCATIONS_FAILURE';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAILURE = 'DELETE_LOCATION_FAILURE';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';

export const GET_SERVICES_EXTRA_SUCCESS = 'GET_SERVICES_EXTRA_SUCCESS';
export const GET_SERVICES_EXTRA_FAILURE = 'GET_SERVICES_EXTRA_FAILURE';
export const CREATE_SERVICES_EXTRA_SUCCESS = 'CREATE_SERVICES_EXTRA_SUCCESS';
export const UPDATE_SERVICE_EXTRAS_SUCCESS = 'UPDATE_SERVICE_EXTRAS_SUCCESS';
export const DELETE_SERVICE_EXTRA_SUCCESS = 'DELETE_SERVICE_EXTRA_SUCCESS';
export const DELETE_SERVICE_EXTRA_FAILURE = 'DELETE_SERVICE_EXTRA_FAILURE';

export const GET_AVAILABILITY_SUCCESS = 'GET_AVAILABILITY_SUCCESS';
export const GET_AVAILABILITY_FAILURE = 'GET_AVAILABILITY_FAILURE';
export const CREATE_AVAILABILITY = 'CREATE_AVAILABILITY';
export const CREATE_AVAILABILITY_SUCCESS = 'CREATE_AVAILABILITY_SUCCESS';
export const CREATE_AVAILABILITY_FAILURE = 'CREATE_AVAILABILITY_FAILURE';
