// Restaurants Action Types
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANTS_FAILURE = 'GET_RESTAURANTS_FAILURE';
export const CREATE_RESTAURANT_SUCCESS = 'CREATE_RESTAURANT_SUCCESS';
export const CREATE_RESTAURANT_FAILURE = 'CREATE_RESTAURANT_FAILURE';
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS';
export const UPDATE_RESTAURANT_FAILURE = 'UPDATE_RESTAURANT_FAILURE';
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS';
export const DELETE_RESTAURANT_FAILURE = 'DELETE_RESTAURANT_FAILURE';

export const GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS';
export const GET_TABLES_FAILURE = ' GET_TABLES_FAILURE';
export const CREATE_TABLE_SUCCESS = 'CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_FAILURE = 'CREATE_TABLE_FAILURE';
export const UPDATE_TABLE_SUCCESS = 'UPDATE_TABLE_SUCCESS';
export const UPDATE_TABLE_FAILURE = 'UPDATE_TABLE_FAILURE';
export const DELETE_TABLE_SUCCESS = 'DELETE_TABLE_SUCCESS';
export const DELETE_TABLE_FAILURE = 'DELETE_TABLE_FAILURE';

export const GET_TIMESLOTS_SUCCESS = 'GET_TIMESLOTS_SUCCESS';
export const GET_TIMESLOTS_FAILURE = ' GET_TIMESLOTS_FAILURE';
export const CREATE_TIMESLOT_SUCCESS = 'CREATE_TIMESLOT_SUCCESS';
export const CREATE_TIMESLOT_FAILURE = 'CREATE_TIMESLOT_FAILURE';
export const UPDATE_TIMESLOT_SUCCESS = 'UPDATE_TIMESLOT_SUCCESS';
export const UPDATE_TIMESLOT_FAILURE = 'UPDATE_TIMESLOT_FAILURE';
export const DELETE_TIMESLOT_SUCCESS = 'DELETE_TIMESLOT_SUCCESS';
export const DELETE_TIMESLOT_FAILURE = 'DELETE_TIMESLOT_FAILURE';

export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAILURE = ' GET_BOOKINGS_FAILURE';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';

export const GET_BOOKINGS_BY_STATUS_SUCCESS = 'GET_BOOKINGS_BY_STATUS_SUCCESS';
export const GET_BOOKINGS_BY_STATUS_FAILURE = ' GET_BOOKINGS_BY_STATUS_FAILURE';

export const GET_REQUESTS_BY_STATUS_SUCCESS = 'GET_REQUESTS_BY_STATUS_SUCCESS';
export const GET_REQUESTS_BY_STATUS_FAILURE = 'GET_REQUESTS_BY_STATUS_FAILURE';
