export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAILURE = ' GET_BOOKINGS_FAILURE';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';

// SPA TREATMENT
export const GET_TREATMENT_CATEGORIES_SUCCESS =
	'GET_TREATMENT_CATEGORIES_SUCCESS';
export const GET_TREATMENT_CATEGORIES_FAILURE =
	'GET_TREATMENT_CATEGORIES_FAILURE';

export const GET_TREATMENT_DATA_SUCCESS = 'GET_TREATMENT_DATA_SUCCESS';
export const GET_TREATMENT_DATA_FAILURE = 'GET_TREATMENT_DATA_FAILURE';

export const GET_TREATMENTS_OF_CATEGORY_SUCCESS =
	'GET_TREATMENTS_OF_CATEGORY_SUCCESS';
export const GET_TREATMENTS_OF_CATEGORY_FAILURE =
	'GET_TREATMENTS_OF_CATEGORY_FAILURE';

// SPA TREATMENT DATA
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAILURE = 'GET_APPOINTMENT_FAILURE';
export const GET_APPOINTMENT_DATA_SUCCESS = 'GET_APPOINTMENT_DATA_SUCCESS';
export const GET_APPOINTMENT_DATA_FAILURE = 'GET_APPOINTMENT_DATA_FAILURE';

// Actiontypes local data
export const FETCH_SPA_LOCAL_BOOKINGS_SUCCESS =
	'FETCH_SPA_LOCAL_BOOKINGS_SUCCESS';
export const FETCH_SPA_LOCAL_BOOKINGS_FAILURE =
	'FETCH_SPA_LOCAL_BOOKINGS_FAILURE';
