export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAILURE = 'GET_CLASSES_FAILURE';

// Booking
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAILURE = ' GET_BOOKINGS_FAILURE';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';

// Action types for local data

export const FETCH_LOCAL_BOOKINGS_SUCCESS = 'FETCH_LOCAL_BOOKINGS_SUCCESS';
export const FETCH_LOCAL_BOOKINGS_FAILURE = 'FETCH_LOCAL_BOOKINGS_FAILURE';

// Personal Trainer Bookings
export const GET_PERSONAL_TRAINERS_BOOKING_SUCCESS =
	'GET_PERSONAL_TRAINERS_BOOKING_SUCCESS';
export const GET_PERSONAL_TRAINERS_BOOKING_FAILURE =
	'GET_PERSONAL_TRAINERS_BOOKING_FAILURE';
// Personal Trainer
export const GET_PERSONAL_TRAINERS_SUCCESS = 'GET_PERSONAL_TRAINERS_SUCCESS';
export const GET_PERSONAL_TRAINERS_FAILURE = 'GET_PERSONAL_TRAINERS_FAILURE';
